### PR TITLE
Region Treatment Code Consistency

### PR DESCRIPTION
**Pull request by AdamHawtin**
## Why
The region needs to match the treatment code otherwise action rules can fail to process.

## What
* Generate region from treatment code in sample generator
* Check region matches treatment code in validator
* Small refactors for consistency

## Wherefore
https://trello.com/c/fUZZsos9/845-fix-region-mismatching-with-treatment-code-in-generated-test-sample-files-5

### CODE REVIEW

**Review by NickGrantX — CHANGES_REQUESTED** [review]
Only minor point is that the whitespace check makes sure there's no _leading_ whitespace as well as trailing.

**Review by NickGrantX — APPROVED** [review]
Great work 👍

**Review by ryangrundy7 — CHANGES_REQUESTED** [review]
Flake issue in test_validators and I got some failing tests still

**Review by ryangrundy7 — APPROVED** [review]
LGTM. 👍

**Comment by AdamHawtin** [comment]
[Fix region mismatching with treatment code in generated test sample files (5)](https://trello.com/c/fUZZsos9/845-fix-region-mismatching-with-treatment-code-in-generated-test-sample-files-5)

**Pull request merged**
